name: Pull Request

on: pull_request

jobs:
  pre-push:
    strategy:
      matrix:
        toolchain:
          - stable
          - 1.92
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.toolchain }}
          components: "rustfmt,clippy"
      - run: sudo apt-get install libvirt-dev fuse3
      - run: make pre-push
